// <auto-generated />
namespace ChulWoo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _180810 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_180810));
        
        string IMigrationMetadata.Id
        {
            get { return "201808100851365_180810"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
